sudo: required
services:
- docker
language: c
compiler: gcc
os:
- linux
script:
- "./docker-build.sh"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT}
  - secure: dnxPUUvj9yoD/O/0FDgiGxsNEtpeBLPjw/YWkMXA1lVD2pwTiNmjfXzRfJszgSlCyGWmeQ5CCImuEw+ZZAbP5yyvF8ocsIHAFn679WJSj4dycTOG3HxDC01Xx64VQoMA2bfMn9FNmmG1UgJpX9mEc06N2jFMUphN0p5aRyBZs4210w9NCPjY/0ybYA5CAhpx2Z3A4N0XPbcLq9w+FE7h+mDJk8iLpnnik1CQxF9ssxtQqmDQEcIjxqASxGWok8jsURMTE9qwZj7gdOvetKCKMs9hp+dBqzPazwnhfEeUF9fc91jlWkxziS5c2MwNSTTzbn6cB2gwoGXQqlTYiytZ/lpfOQthxCL1sicOpR5iUQXgYxuiRMxf2HdZCh6F5Bo6M24AytTG2RXQJdWG+e0H18oM1RdapkvB62l3r6rfg8VuydkqhqhHzKjox+9XRt5SD1ZC7SQ7YP0fHkzKQNh+L0t3WadhWN5p5s9U61QvFiGfLjRViOsEdZ+GdfI822Lv1AscU/EUXdtG/6qP9W8paJ6DvR8ZivpKmJen1Nci7aB3YLyT0IrCHcwBIQBYiXEABNi+7effXSRIZWC5aKkFt5n8Qj0XdaFmE3EkG2uDhHVp6pJRoBIsD0KrV6ysdpAl6a334qJRlocihqFlhygbhP8gtQOCj7FwgQCIQg3lt0w=
  - secure: VrHDA9/V3dvjfMdzna9aOEPYAoTHaocTgMiGZ+A7NR7MrdZSGNsoq6YfZg+uBl7v6T/Zx7iY1LD11KxMQjeaeC5NxmYyjXLrdMS84mPiEUlkak7bcmxaCGMRsnQw/9VQdQsnUhlvEKizosd/bJfu2GZN18SPwibtplq/V2tdIwK2Af8quprTHrJ25Ea3i6PMwQ3XqTOS119XL3tH5jAhawSX8YZf35+NKcDy2IdbvKKMsyKKvzgCtMLimbWcV4oQ47oQLvuJyXoKzqRt4iyk91KihG9ZIOu+/F1KanhBwRghc6qEkSX0nsu2c3Nu4g0Cxq7tO7EHy+3Q5JOTOg4yG5AhBHawFQez7ts9tr7WdXzRcphe/UyfBq5PALGO9pljtEXfKPaqI2jtUDM9BfJcvnm+2q8s61Mofcj3u5vcnJmNpQABrwI4YjdxUCYcUwh/XYmsPMOnVo8YfGGhncI+8FfykiwOO8y9WxNvaI30gXxOZVUk/NgBRttyC6IHHmLOmyPnp16WmLpaBKA4Ft19NonNeeb2xJmQsRgPVflvZ0QaBdA6WI5zu3yguQdRmBQ/3AEUYPec6ftYayme1j0SE+7h761A5B5/KRTkhFWcHxIiZJYNF5vclAmM/8MJBDvgGJvIf6TKO7tzesHAZ1YcKj3SR/m6f/YOz7RMR3Esp7w=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=dougefresh/presentation-serverless
- echo $COMMIT
- docker push $REPO:latest
