sudo: required
services:
- docker
language: c
compiler: gcc
os:
- linux
script:
- "./docker-build.sh"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT}
  - secure: Tctcq9FKlakT24jfMdQN6GGNT6Ck2ppYZIX39Q1v/OqX40bVWmM5YQEsY6wxyeAXJnBLIYQl2irj6iPUaODtcq1OR25oLvB7o7wAQdvo13O3HwNBtjiHwzUdzV/HG960iTzDU7Dd3z1GezOnRS/BCCcvrYgghiEvESOu7On4/Vu5lUz+4yeVTIXREjWdeUsVPkwRlylwGZFRsfG8YD3cDJyUqT1YD4BxWH6ug0vAnRdf30DiACRqkpwjG/7KOmXLgce+yZVDmpUywhuao612rBWjj+Tjk5CZVQdiwqeqKu57ruhsEQ3QFvEt0unYxwWnEfq/Qdf07rsuZDX/zVzkaB0uZ2EhGWwqVWjuYEALQW33MV5awRA4L5Qr8Bdlfsb1nUYxOVKmPda4tXqtjlWQdBLD30LZ10FXTJce4/uuW4Wf8oJdyRq1uU2iRWcveubQDyg31dceNS+S/2JDHmCcn8LlCka8h+ucx1QSwfmS0l0mh7I3OYZ35uwA/rbl4zNsF1fI4Kj7m6sRySSaUjFyAP1fB9Ulkv5NcnPlkrFvLlT5+tQZzgMx6d+ZfZw6QCMdK4z6IVjHubX4X24UqF393rXZLA2CeLxvKGFdQKNrpf/NmyzikHGm5Aw6ReQUo4XR3IJ4RUZ0IYyo+rMzw+5J8Rgin7Ev3MV5D9m2X52ToUA=
  - secure: nH4ncyB7vQwm45Lv945zRKhwkMyT2HNvSRYMWjjbjJ7FihYHZvWBuM6/gVtoJnX3MW0d0sg15ydSmWB9QouQ9BlxmM60JgCRGY/VWAMNwAOlLWQ6akurZP0cCT7nEwcQsyq1xS6FzhGNbyr8XMakYvxW2F/64VpYeUluKhnZhtJzCAuku0XsCf0gIDzuNngl7WJ+G8ktdtWOD9Jt63A51U/ZNEv1rTvwvvJUErDrhjCq4NRGCe4nTx8ph32uA3b4/31pTO896i+VMaPbyaGNcPas84RVMYi6UF9HvyaeZR9GO2mv4l9mBshwKHMAsRSv1FzrMlf5vWaIi6H++hCApeKGzxHpmpYsIA4lj+8LRiApScZSL+2EOZ1wcGFrh/kOhLMOrsKmQU/LIFskp9HrAw62sxF/fsPKFGLtrmaAigQgUxriM6Tv/Lx+nim8czBshuHRRV4DrBaZeiM5AbxLqnyX7e2skpCuYACyUkLoBICdOIN7XTSSKa1JtsJYqmnF4E/vTIQS1BoZfkjlsxM21IJ7NssniMHPH4F6rvoiRheFjEyZEJcYH6qsbLBRTI57ITQyEgV+M7jOYHkiQ98Axwx5ryJF6z6DwgtUTUtLcsMDbdBibH1gKlSHdwynBWzcnliuA2VVS9xMoPKVhF6eGzz3MEj8MsrUruim1GVWr6M=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push dougefresh/presentations:latest
